import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}

function Header() {
  // Client boundary for signOut button
  return (
    <div className="w-full border-b">
      <div className="mx-auto max-w-5xl px-4 h-14 flex items-center gap-3">
        <Link href="/" className="font-medium">
          Adona
        </Link>
        <div className="ml-auto flex items-center gap-2">
          <Link href="/login">
            <Button variant="ghost" className="h-8">
              Login
            </Button>
          </Link>
          <Link href="/register">
            <Button variant="ghost" className="h-8">
              Register
            </Button>
          </Link>
          <Link href="/chat">
            <Button className="h-8">Chat</Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
